### ISSUE TITLE
send to bluetooth device not working in 3.10

### ISSUE THREAD

**Issue by timcowchip** [gpodder/gpodder#375]
I have built and installed gpodder-3.10.0 in Slackware-14.2 along with python3, dbus-python3, pygobject3-python3 and gnome-bluetooth. "Send to bluetooth device" worked fine with gpodder-3.93.

**Comment by timcowchip** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/site-packages/gpodder/gtkui/main.py", line 1812, in <lambda>
    util.run_in_background(lambda: convert_and_send_thread(episodes_to_copy))
  File "/usr/lib64/python3.6/site-packages/gpodder/gtkui/main.py", line 1800, in convert_and_send_thread
    destfile = self.build_fileName(episode.sync_filename(), ext)
AttributeError: 'gPodder' object has no attribute 'build_fileName'

**Comment by elelay** [comment]
@timcowchip thanks for the report and sorry for the delay: it was a simple typo of the `build_filename` method.
I don't have bluetooth on my computer but faked the sendto-bluetooth command and it seems to work.
If you have time to try again with code from master, let us know if it works for you.

**Comment by timcowchip** [comment]
Yes, thank you Eric it does work with the code from master.
Looking forward to a version upgrade that includes this fix, so that 
I can repackage gPodder for Slackware.
