### PR TITLE
Fix unable to drag and drop from episode list

### PR DESCRIPTION
**Pull request by jawbkr**
Attempting to drag and drop an episode to the playlist of an external media player is no longer working in 3.10.x and causes:

```
Traceback (most recent call last):
  File "/home/jawbkr/github/gpodder/src/gpodder/gtkui/main.py", line 1023, in drag_data_get
    selection_data.set(selection_data.target, 8, '\r\n'.join(uris))
AttributeError: 'SelectionData' object has no attribute 'target'
```

### CODE REVIEW

**Comment by elelay** [comment]
Good catch, thanks!
