### ISSUE TITLE
1.1-adaptive: when using the last commit, Preferences window does not show

### ISSUE THREAD

**Issue by paper42** [gpodder/gpodder#969]
The last commit in 1.1-adaptive branch (4a1a0ba9127d46aec80dca0bd3830bce9b31f34c) causes Preferences window not to open with the following traceback.
```
Traceback (most recent call last):
  File "/home/michal/build/gpodder/src/gpodder/gtkui/app.py", line 269, in on_itemPreferences_activate
    gPodderPreferences(self.window.gPodder,
  File "/home/michal/build/gpodder/src/gpodder/gtkui/interface/common.py", line 37, in __init__
    GtkBuilderWidget.__init__(self, gpodder.ui_folders, gpodder.textdomain, parent, **kwargs)
  File "/home/michal/build/gpodder/src/gpodder/gtkui/base.py", line 71, in __init__
    self.new()
  File "/home/michal/build/gpodder/src/gpodder/gtkui/adaptive/preferences.py", line 201, in new
    index = self.audio_player_model.get_index(self._config.player.audio)
AttributeError: 'str' object has no attribute 'audio'
```
Similar changes are in https://github.com/gpodder/gpodder/pull/963 @tpikonen 
Reverting the commit solves it.

**Comment by tpikonen** [comment]
Thanks for the report.

The 1.1-adaptive branch is now rebased on top of the adaptive branch and contains the 2 commits #963 which properly remove legacy audio and video player config variables. It should work now, but if it doesn't, let me know.
