### ISSUE TITLE
AttributeError: type object 'gPodderSyncUI' has no attribute 'DL_ADDED_ONE'

### ISSUE THREAD

**Issue by thp** [gpodder/gpodder#1137]
Introduced by #1054.

Steps to reproduce:

1. Download a file
2. Pause the download
3. Try to resume the download

```
Traceback (most recent call last):
  File ".../gpodder/src/gpodder/gtkui/main.py", line 1622, in <lambda>
    item.connect('activate', lambda item: self._for_each_task_set_status(tasks, status, force_start))
  File ".../gpodder/src/gpodder/gtkui/main.py", line 1567, in _for_each_task_set_status
    self.set_download_list_state(gPodderSyncUI.DL_ADDED_ONE)
AttributeError: type object 'gPodderSyncUI' has no attribute 'DL_ADDED_ONE'

```

**Comment by auouymous** [comment]
Fixed by #1149.
