### ISSUE TITLE
Hacker Public Radio feed stopped working.

### ISSUE THREAD

**Issue by glotim** [gpodder/gpodder#254]
Hacker Public Radio feed stopped working on gPodder v 3.9.3 on or around 2017-03-05. It had been working fine for years. Here is the log info:

2017-03-26 19:12:20,107 [gpodder.download] ERROR: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error while downloading "Hr1: News Roundup, Residents Hours, BP Oil Spill, Gerrymandering": None
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gpodder/download.py", line 772, in run
    self.tempname, reporthook=self.status_updated)
  File "/usr/lib/python2.7/dist-packages/gpodder/download.py", line 274, in retrieve_resume
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 359, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 372, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 665, in http_error_301
    return self.http_error_302(url, fp, errcode, errmsg, headers, data)
  File "/usr/lib/python2.7/urllib.py", line 635, in http_error_302
    data)
  File "/usr/lib/python2.7/dist-packages/gpodder/download.py", line 234, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 437, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1220, in connect
    self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

**Comment by vossad01** [comment]
What is your Python version?  Can you update it?  I suspect this is the same as #234.

**Comment by glotim** [comment]
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2

Not sure on how to update it in Linux Mint.

**Comment by vossad01** [comment]
Assuming you are using the package manger, the command to upgrade only python is: `apt install --only-upgrade python`

I know Linux Mint 18+ has a package for a new-enough python.  I don't know about older versions.

**Comment by glotim** [comment]
Still on v 17.3 so it says I have the latest python.
Time to think about an OS upgrade.

**Comment by vossad01** [comment]
I believe Mint's Update Manager can handle upgrading major versions and I am all for people keeping up to date.  However I recognize there are risks and other considerations. 

For completeness of this issue your other options would be:
 * to find a [backports] PPA with a newer python (you need at least 2.7.9)
 * install a newer python manually
 * [run gPodder from a git clone](https://github.com/gpodder/gpodder/wiki/Run-from-Git) and switch to the `gtk3` branch that runs under Python 3

**Comment by elelay** [comment]
Fixed in the 3.10 branch with the switch to python 3.
